*{box-sizing:border-box} :root{--ink:#3f4058;--muted:#7c7d92;--line:#e9e6ef;--card:#fff;--bg:#fffaf6;font-family:"Pretendard","Noto Sans KR",system-ui,sans-serif}
body{margin:0;background:linear-gradient(180deg,#fff7f0,#f7fbff);color:var(--ink)}button,input{font:inherit}.hidden{display:none!important}.app{max-width:1200px;margin:auto;padding:18px}
.topbar{display:flex;align-items:center;gap:14px;background:#fff;border:1px solid var(--line);border-radius:24px;padding:14px 18px;box-shadow:0 12px 28px #765b4b12}.topbar h1{font-size:1.35rem;margin:0}.topbar h1 span{font-size:.65rem;background:#ff8a65;color:#fff;padding:5px 8px;border-radius:14px}.topbar p{margin:3px 0 0;color:var(--muted)}.home-logo{border:0;background:#fff0d8;width:54px;height:54px;border-radius:18px;font-size:29px}.parent-btn{margin-left:auto;border:0;background:#f1edff;color:#6f55bd;border-radius:14px;padding:11px 14px;font-weight:900}
main{padding-top:18px}.welcome{background:linear-gradient(135deg,#ffe7d7,#fff4a8);border-radius:28px;padding:28px 34px;display:flex;justify-content:space-between;align-items:center}.welcome small{font-weight:900;color:#f06f45}.welcome h2{font-size:1.8rem;margin:8px 0}.welcome p{margin:0;color:#735e57}.welcome-animals{font-size:54px;white-space:nowrap}
.mini-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:16px 0}.mini-stats div{background:#fff;border:1px solid var(--line);border-radius:18px;padding:14px;text-align:center;font-size:1.15rem}.mini-stats b{font-size:1.45rem}.mini-stats small{display:block;color:var(--muted)}
.world-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.world{position:relative;border:0;border-radius:30px;padding:22px;text-align:left;min-height:270px;color:#43445b;cursor:pointer;box-shadow:0 14px 30px #655f6d18;transition:.18s;overflow:hidden}.world:hover{transform:translateY(-5px) rotate(-.4deg)}.world:after{content:"";position:absolute;width:110px;height:110px;border-radius:50%;right:-25px;bottom:-30px;background:#ffffff55}.planet-face{position:absolute;right:20px;top:18px;font-size:36px}.world-symbol{width:74px;height:74px;border-radius:25px;background:#ffffffaa;display:grid;place-items:center;font-size:42px;font-weight:900}.world h3{font-size:1.35rem;margin:16px 0 6px}.world p{min-height:48px;margin:0;color:#63647a}.topics{display:flex;gap:6px;flex-wrap:wrap;margin-top:18px}.topics span{background:#ffffffb8;border-radius:20px;padding:6px 9px;font-size:.72rem;font-weight:800}.add{background:linear-gradient(145deg,#ffd5e2,#ffe8b8)}.sub{background:linear-gradient(145deg,#cfefff,#e4e3ff)}.mul{background:linear-gradient(145deg,#d8f4df,#fff1bd)}.div{background:linear-gradient(145deg,#ffe6a8,#ffd5c8)}.sense{background:linear-gradient(145deg,#e6dcff,#ffd9f1)}.explore{background:linear-gradient(145deg,#c9f3ee,#dcecff)}
.world-header{display:flex;align-items:center;gap:20px;margin-bottom:14px}.world-header>button{border:0;background:#fff;border-radius:14px;padding:11px 14px;color:#6a5eb2;font-weight:900;box-shadow:0 6px 14px #463d5c12}.world-title-wrap{display:flex;align-items:center;gap:14px}.big-mascot{width:74px;height:74px;border-radius:25px;background:#fff;display:grid;place-items:center;font-size:42px;box-shadow:0 10px 22px #655f6d17}.world-title-wrap small{font-weight:900;color:#ff7c55}.world-title-wrap h2{margin:3px 0}.world-title-wrap p{margin:0;color:var(--muted)}
.lesson-tabs{display:flex;gap:9px;background:#fff;border:1px solid var(--line);padding:8px;border-radius:18px;margin-bottom:14px}.lesson-tab{flex:1;border:0;background:transparent;border-radius:13px;padding:13px;font-weight:900;color:#77788b}.lesson-tab.active{background:#6f63cc;color:#fff}
.panel{background:#fff;border:1px solid var(--line);border-radius:26px;padding:22px;min-height:490px}.concept-layout{display:grid;grid-template-columns:.75fr 1.25fr;gap:20px}.concept-menu{display:flex;flex-direction:column;gap:10px}.concept-btn{border:0;background:#f7f5fb;text-align:left;padding:14px;border-radius:15px;font-weight:900;color:#65667a}.concept-btn.active{background:#ffe9d9;color:#d8663e}.concept-card{background:linear-gradient(145deg,#fffaf5,#f6f8ff);border-radius:22px;padding:22px;min-height:410px}.concept-card h3{margin-top:0}.concept-card>p{color:var(--muted)}
.place-model{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.place-col{background:#fff;border-radius:16px;padding:12px;text-align:center}.objects{min-height:150px;display:flex;flex-wrap:wrap;gap:5px;align-content:flex-start;justify-content:center}.one{width:20px;height:20px;background:#ff9f43;border-radius:5px;box-shadow:inset 0 -3px #d56d0c}.ten{width:18px;height:110px;background:repeating-linear-gradient(#55aef2 0 9px,#2c82c4 9px 11px);border-radius:5px}.hundred{width:100px;height:100px;border-radius:8px;background:linear-gradient(#8e80cf 1px,transparent 1px),linear-gradient(90deg,#8e80cf 1px,transparent 1px),#dcd6f7;background-size:10px 10px}
.step-strip{display:flex;gap:9px;margin-top:15px}.step{flex:1;background:#fff;border-radius:14px;padding:12px;text-align:center}.step b{display:block;color:#6a5bc5;font-size:1.25rem}
.array{display:grid;gap:5px;justify-content:center;margin:20px auto}.array i{width:21px;height:21px;background:#6f63cc;border-radius:50%}.area-model{display:grid;grid-template-columns:3fr 1fr;grid-template-rows:2fr 1fr;height:280px;gap:5px}.area-cell{display:grid;place-items:center;border-radius:17px;font-weight:900;font-size:1.15rem}.area-cell:nth-child(1){background:#dcd8ff}.area-cell:nth-child(2){background:#cff0ff}.area-cell:nth-child(3){background:#ffe3bf}.area-cell:nth-child(4){background:#d4f4df}
.share-wrap{display:flex;justify-content:center;gap:12px;flex-wrap:wrap;margin:18px 0}.cup{width:88px;min-height:125px;border:3px solid #e59a2e;border-top:0;border-radius:10px 10px 30px 30px;background:#fff7d9;padding:8px;text-align:center}.snack{display:inline-block;font-size:19px}
.numberline{height:110px;position:relative;margin:40px 20px;border-bottom:5px solid #78839c}.tick{position:absolute;bottom:-18px;width:38px;height:38px;border-radius:50%;background:#6f63cc;color:#fff;display:grid;place-items:center;font-size:.68rem}.arc{height:75px;border:4px solid #ff9b4a;border-bottom:0;border-radius:50% 50% 0 0;margin:0 15% -5px}
.play-box{text-align:center}.play-box h3{font-size:1.45rem}.counter{display:flex;justify-content:center;gap:10px;margin:20px}.counter button{width:60px;height:60px;border:0;border-radius:20px;background:#eeeaff;color:#6559bf;font-size:1.8rem;font-weight:900}.counter output{min-width:120px;background:#fff5dd;border-radius:20px;display:grid;place-items:center;font-size:2rem;font-weight:900}.play-result{background:#f7f5fb;border-radius:20px;padding:22px;min-height:180px}
.quiz-layout{display:grid;grid-template-columns:.8fr 1.2fr;gap:18px}.question-box{background:#fff9f1;border-radius:22px;padding:22px}.question-box>span{color:#f07951;font-weight:900}.problem-text{font-size:3rem;font-weight:950;margin:22px 0}.question-box p{color:var(--muted)}.answer-row{display:flex;gap:8px}.answer-row input{min-width:0;flex:1;border:2px solid #e8e2ee;border-radius:14px;padding:13px;font-size:1.2rem}.answer-row button{border:0;border-radius:14px;padding:12px 17px;font-weight:900;background:#6f63cc;color:#fff}.answer-row .soft-btn{background:#eae7f8;color:#655abb}.feedback{display:none;margin-top:14px;border-radius:14px;padding:13px;font-weight:900}.feedback.show{display:block}.feedback.good{background:#e8faf1;color:#17704e}.feedback.bad{background:#fff0f0;color:#a33b49}.quiz-visual{background:#f7f8ff;border-radius:22px;padding:20px;min-height:390px;display:flex;flex-direction:column;justify-content:center}
.secret-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.secret{background:#fff;border-radius:16px;padding:17px;text-align:center}.secret small{color:var(--muted)}.secret b{display:block;font-size:1.45rem;margin-top:5px}
.report-cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.report-cards div,.report-box{background:#fff;border:1px solid var(--line);border-radius:20px;padding:20px}.report-cards b{display:block;font-size:1.8rem}.report-box{margin-top:14px}.mode-row{display:grid;grid-template-columns:110px 1fr 55px;gap:10px;align-items:center;margin:13px 0}.bar{height:12px;background:#ebe9f2;border-radius:10px;overflow:hidden}.bar i{display:block;height:100%;background:#7668d3}
@media(max-width:900px){.world-grid{grid-template-columns:repeat(2,1fr)}.concept-layout,.quiz-layout{grid-template-columns:1fr}.concept-menu{display:grid;grid-template-columns:repeat(2,1fr)}.report-cards{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.app{padding:9px}.topbar p,.parent-btn{font-size:.75rem}.welcome{padding:22px}.welcome-animals{display:none}.welcome h2{font-size:1.4rem}.world-grid{grid-template-columns:1fr}.lesson-tabs{overflow:auto}.lesson-tab{min-width:145px}.place-model{grid-template-columns:1fr}.report-cards{grid-template-columns:1fr}.problem-text{font-size:2.3rem}.concept-menu{grid-template-columns:1fr 1fr}.world-title-wrap p{display:none}}
